go_library(
    name = "logging",
    srcs = [
        "formatter.go",
        "logging.go",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//common/go/contexttag",
        "//third_party/go:github.com__joonix__log",
        "//third_party/go:github.com__sirupsen__logrus",
        "//third_party/go:github.com__sirupsen__logrus__hooks__writer",
    ],
)
