plugin_repo(
    name = "shell",
    owner = "please-build",
    revision = "v0.2.0",
)

plugin_repo(
    name = "python",
    revision = "v1.6.0",
)

plugin_repo(
    name = "go",
    owner = "please-build",
    plugin = "go-rules",
    revision = "v1.23.0",
)

plugin_repo(
    name = "proto",
    owner = "malonaz",
    revision = "6937727ab903e8299999fa5d24b4d249309625cb",
)
