plugin_repo(
    name = "shell",
    owner = "please-build",
    revision = "v0.2.0",
)

plugin_repo(
    name = "python",
    revision = "v1.6.0",
)

plugin_repo(
    name = "go",
    owner = "please-build",
    plugin = "go-rules",
    revision = "v1.23.0",
)

plugin_repo(
    name = "proto",
    owner = "malonaz",
    revision = "f12c8c4444a32c2a40f468ef5ff865f7a6533c26",
)
