plugin_repo(
    name = "shell",
    owner = "please-build",
    revision = "v0.2.0",
)

plugin_repo(
    name = "python",
    revision = "v1.6.0",
)

plugin_repo(
    name = "go",
    owner = "please-build",
    plugin = "go-rules",
    revision = "v1.23.0",
)

plugin_repo(
    name = "proto",
    owner = "malonaz",
    revision = "b0f1d27feea437c2230a355f02acb7db1bfa8b1a",
)
