package(default_visibility = ["PUBLIC"])

filegroup(
    name = "template",
    srcs = ["template.build_defs"],
)

filegroup(
    name = "docker",
    srcs = ["docker.build_defs"],
)

filegroup(
    name = "k8s",
    srcs = ["k8s.build_defs"],
)

filegroup(
    name = "remote",
    srcs = ["remote.build_defs"],
)

filegroup(
    name = "utils",
    srcs = ["utils.build_defs"],
)
