package(default_visibility = ["PUBLIC"])

proto_library(
    name = "aip",
    srcs = ["aip.proto"],
    deps = [
        "//third_party/proto/googleapis:v1alpha1",
    ],
)

proto_library(
    name = "nats",
    srcs = ["nats.proto"],
)
