package(default_visibility = ["PUBLIC"])

export_file(
    name = "utils.go.tmpl",
    src = "utils.go.tmpl",
)

############# SERVICE #################
export_file(
    name = "main.go.tmpl",
    src = "main.go.tmpl",
)

export_file(
    name = "service.go.tmpl",
    src = "service.go.tmpl",
)

export_file(
    name = "k8s.yaml.tmpl",
    src = "k8s.yaml.tmpl",
)

export_file(
    name = "service_manifest.schema",
    src = "service_manifest.schema",
)

############# ADMIN_API #################
export_file(
    name = "admin_api_main.go.tmpl",
    src = "admin_api_main.go.tmpl",
)

export_file(
    name = "admin_api_manifest.schema",
    src = "admin_api_manifest.schema",
)
